---
  - name: Install Packages
    hosts: all
    vars_files: vars.yml
    tasks:
      - name: Install python and deps
        package: 
          name: "{{ item }}"
        loop: "{{ var_python_deps }}"
      - name: Install sql
        package: 
          name: "{{ item }}"
        loop: "{{ var_database_deps }}"
  - name: Configure Database
    hosts: all
    vars_files: vars.yml
    tasks:
      - name: Configure MySQL Service
        service:
          state: started
          enabled: yes
          name: mysql
        become: yes
      - name: Create Database
        mysql_db:
         name: "{{ var_db_name }}"
         state: present
      - name: Configure db user
        mysql_user:
          name: "{{ var_db_user }}"
          password: "{{ var_db_password }}"
          state: present
          priv: '*.*:ALL,GRANT'
      - name: Create employees table
        command: mysql -u {{var_db_user}} -p {{var_db_password}} {{var_db_name}} --skip-column-names --execute "create table employees (name VARCHAR(20))"
      - name: Add John to employees table
        command: mysql -u {{var_db_user}} -p {{var_db_password}} {{var_db_name}} --skip-column-names --execute "INSERT INTO employees VALUES ('JOHN')"
        

        